#!bin bash

# quality control with fastqc
##It is assumed that all softwares for this analysis are installed
mkdir Fastqcresults #create a repertory named "Fastqcresults" for generated results saving
for f in *fastq.gz ; do
    fastqc -o ./FastqcResults/ "${f}"
done

# aggregate quality control results with multiqc
##It is assumed that all softwares for this analysis are installed and that we are currently in the directory Fastqcresults
multiqc . #to perform multiqc analysis based on previous plots generated by fastqc

exit 0
