#!/bin/bash -

# quality control with fastqc

# how to install?
#
# indicate here or in another script the command lines used to
# install fastqc and multiqc
#

mkdir Fastqcresults  # what if the folder already exists?

for f in *fastq.gz ; do
    fastqc -o ./Fastqcresults/ "${f}"
done

# aggregate quality control results with multiqc
##It is assumed that all softwares for this analysis are installed and that we are currently in the directory Fastqcresults
multiqc . #to perform multiqc analysis based on previous plots generated by fastqc

exit 0
